# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Carlos < Formula
  desc "Pure-Go TUI agent with skill induction and sub-agent supervision."
  homepage "https://github.com/georgebuilds/carlos"
  version "0.8.4"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/georgebuilds/carlos/releases/download/v0.8.4/carlos_0.8.4_darwin_x86_64.tar.gz"
      sha256 "08bb7f66b9bb8443e19867316bc7c3a066af79fbacebd400af94a4d5bb4eb2d1"

      define_method(:install) do
        bin.install "carlos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/georgebuilds/carlos/releases/download/v0.8.4/carlos_0.8.4_darwin_arm64.tar.gz"
      sha256 "3a2c86fd466b9d2f8f692c26c8869e771e155ce6c7be1843c1edf1044dd103fc"

      define_method(:install) do
        bin.install "carlos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/georgebuilds/carlos/releases/download/v0.8.4/carlos_0.8.4_linux_x86_64.tar.gz"
      sha256 "3d24ec1f36a8bea0befe2a01295b280ac165d0ecbca2954ec82fe9a45035b474"
      define_method(:install) do
        bin.install "carlos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/georgebuilds/carlos/releases/download/v0.8.4/carlos_0.8.4_linux_arm64.tar.gz"
      sha256 "faf7a334779899940c354084490e86764bc7c9b28c8be2f585e8da38d28dbafc"
      define_method(:install) do
        bin.install "carlos"
      end
    end
  end

  test do
    system "#{bin}/carlos", "version"
  end
end
